### ISSUE TITLE
Resource packs don't load in server.

### ISSUE THREAD

**Issue by Mapleshade20** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#1]
(The resource pack can be successfully loaded with my original client.)
However, after I fill the url in "resource-pack" of Server.properties, either when I enter the world or when other players join my LAN server, the pack isn't loaded at all.
![image](https://user-images.githubusercontent.com/62641761/140642639-c1c856e9-ff24-4bb9-afcc-9dcace557f40.png)

P.S. you can find the resource pack at https://gitee.com/zhangchenhao15/lol/raw/master/Tank.zip

**Comment by shuen4** [comment]
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/releases/tag/2.67b
1.13-1.16 未测试
1.17 测试通过(使用https://gitee.com/zhangchenhao15/lol/raw/master/Tank.zip)

**Comment by Mapleshade20** [comment]
thanks =)
