### ISSUE TITLE
提议新功能

### ISSUE THREAD

**Issue by OrokinLF** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#11]
希望能够在游戏内输入指定IP进入其他服务器,并保存地图
此用途能够帮助在网易中的局域网进行服务端对接的玩家便捷的进入
望采纳

**Comment by shuen4** [comment]
> 游戏内输入指定IP进入其他服务器,并保存地图

我没用过网易版, 不了解这里的意思
说的详细一些?

**Comment by OrokinLF** [comment]
网易版退到主页面或者多人页面会自动关闭游戏,建议使用某个按键打开直接链接页面(多人游戏里的),从而保存地图并进入服务器

**Comment by OrokinLF** [comment]
就是说玩家按某个键打开输入IP的页面,玩家输入IP,直接进入到某个服务器

**Comment by shuen4** [comment]
[test.zip](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/files/10268332/test.zip)
测试一下看能不能使用

**Comment by OrokinLF** [comment]
是适用在哪个版本

**Comment by OrokinLF** [comment]
只有1.19可以正常运行,但不确定网易端会不会关掉游戏

**Comment by OrokinLF** [comment]
网易最高版本是1.18.1

**Comment by shuen4** [comment]
[test.zip](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/files/10270516/test.zip)

**Comment by OrokinLF** [comment]
可以正常使用,谢了,麻烦也加到1.12.2,1.16.4版本里把

**Comment by shuen4** [comment]
[KeyBindDirectJoinServer.zip](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/files/10277337/KeyBindDirectJoinServer.zip)

**Comment by OrokinLF** [comment]
可以的

**Comment by OrokinLF** [comment]
对了,还有1.16.4的

**Comment by shuen4** [comment]
[KeyBindDirectJoinServer 1.16.5.zip](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/files/10298735/KeyBindDirectJoinServer.1.16.5.zip)
forge 1.16.4无mod一开就崩 无法测试

**Comment by OrokinLF** [comment]
虽然得在网易手动改forge与json,但还是想麻烦问下能否直接发下1.16.4的KeyBindDirectJoinServer,谢谢了

**Comment by shuen4** [comment]
1.16.4 (forge 35.1.37, 35.1.4) 无法初始化开发环境,因此无法制作1.16.4版的

**Comment by OrokinLF** [comment]
好的
