### ISSUE TITLE
使用/reload后会导致服务器命令无法使用

### ISSUE THREAD

**Issue by Koud-Wind** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#12]
使用/reload后会导致服务器命令无法使用, 此外, 构建时的ForgeGradle/Gradle版本应该选用哪个

**Comment by shuen4** [comment]
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.13/build.gradle#L70
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.14/build.gradle#L92
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.15/build.gradle#L94
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.16/build.gradle#L120
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.17/build.gradle#L131
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.18/build.gradle#L131
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.19/build.gradle#L142
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.20/build.gradle#L163
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.20/gradle.properties#L10
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/679acd980b95f16fe385263aa0fc13b2c16aa22b/1.20/gradle.properties#L16
我是直接下载mdk包，并不知道ForgeGradle/Gradle的版本

**Comment by Koud-Wind** [comment]
我始终无法构建AIO版本, 我需要导入其他版本的forge库, 
![image](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/assets/123817318/df62e947-1e33-4b41-8b3a-359553665d23)
如何配置好环境
