### ISSUE TITLE
添加对 Minecraft 1.20.6 的支持

### ISSUE THREAD

**Issue by LTHPKBTE** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#13]
如上，实测 Forge 50.0.7 版本 1.20.6 无法使用 v2.73_1.20 版模组。日志文件如下：
[latest.log](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/files/15234205/latest.log)

**Comment by shuen4** [comment]
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/releases/download/2.73/ServerPropertiesLAN_v2.73_1.20.6.jar
