### ISSUE TITLE
need to load resourcepacks in versions before 1.17

### ISSUE THREAD

**Issue by Mapleshade20** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#3]
Dear owner of this project:
I noticed "#2: setting resource pack will make client crash (resource pack dialog)" in the bug list.
Do you mean versions before 1.17 do not support designating a resource pack in Server.p ?
If I understand that sentence correctly, would you please fix the issue?

**Comment by shuen4** [comment]
1.13 - 1.16 服主点了游戏就会崩溃
![1](https://user-images.githubusercontent.com/38818683/145732895-5d1ea544-293a-4f6d-bcaa-34c7b00fcc8d.png)

**Comment by shuen4** [comment]
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/releases/tag/2.69
解决方式为取消服主的资源包提示，所以服主需要自行进资源包设置应用
