### ISSUE TITLE
[Feature Suggest] Add require-resource-pack option

### ISSUE THREAD

**Issue by Mapleshade20** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#4]
Dear Owner,
I really like your efforts to maintain this mod. Yet I think you can create more features in server.p
This is the comparison between real serverjar and this mod. 
![image](https://user-images.githubusercontent.com/62641761/146636745-ecca916b-b765-47b9-bd4c-58cc88a49bcc.png)
I suggest you add a "require-resource-pack=true/false" and "whitelist=true/false", and if you have problems coding them, you may check how Mojang does it in https://www.aliyundrive.com/s/GkEnqrenxL3

**Comment by Mapleshade20** [comment]
You may try it out in version 1.17 and 1.18, which are most commonly used right now.

**Comment by shuen4** [comment]
> whitelist=true/false

![image](https://user-images.githubusercontent.com/38818683/146683409-1a425a0e-9804-4bb0-9edc-8c465e6c9803.png)

**Comment by shuen4** [comment]
no response, assuming it has been resolved
closing this issue
