### ISSUE TITLE
[1.12.2]Please update ServerPropertiesLANv2.65 to 2.70

### ISSUE THREAD

**Issue by OrokinLF** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#5]
Can you update ServerPropertiesLAN to v2.70，You can't install resource packs for others.I really need

**Comment by shuen4** [comment]
fix resource pack & add mod option register-additional-command
tested only 1.12.2
[ServerPropertiesLAN-2.65_E.zip](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/files/7777516/ServerPropertiesLAN-2.65_E.zip) (github doesn't support attach .jar file)

**Comment by OrokinLF** [comment]
> 修订资源包和添加 mod 选项注册附加命令仅测试 1.12.2 [ServerPropertiesLAN-2.65_E.zip（github](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/files/7777516/ServerPropertiesLAN-2.65_E.zip)不支持附加.jar文件）

thank you:]
