### ISSUE TITLE
no permission to use /ban

### ISSUE THREAD

**Issue by OrokinLF** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#6]
I am here about the source code of the server command, I think you may be interested in this

https://github.com/a08381/Operator/releases

**Comment by shuen4** [comment]
this?
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/1c5fa697711601ee84cf07658a0a1f8ab9c4c5db/1.18/src/main/java/com/shuen/splan/splan.java#L13-L25
https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/blob/1c5fa697711601ee84cf07658a0a1f8ab9c4c5db/1.18/src/main/java/com/shuen/splan/splan.java#L214-L226

**Comment by OrokinLF** [comment]
Yes

**Comment by shuen4** [comment]
i just re-add the dedicated server commands
these commands already exist in the minecraft client

**Comment by OrokinLF** [comment]
But it cannot be used in the Minecraft client.

**Comment by OrokinLF** [comment]
local area network

**Comment by shuen4** [comment]
if you need #5 have these commands
open server.properties and set register-additional-command to true

**Comment by OrokinLF** [comment]
Unbelievable,But about /ban is not available.

**Comment by shuen4** [comment]
> not available.

you mean ![image](https://user-images.githubusercontent.com/38818683/151657646-07c9c458-201c-4ffa-9d17-8eb15968dc96.png) ?

**Comment by shuen4** [comment]
note that chinese language can be used here

**Comment by OrokinLF** [comment]
好的，使用/ban时没有权限

**Comment by OrokinLF** [comment]
是因为客户端的特性吗

**Comment by shuen4** [comment]
看了指令的代码
找到权限要求是专用服务器和权限级别3
1.16+没要求要专用服务器

如需修复可以说一声

**Comment by OrokinLF** [comment]
如果可以修复那太好了

**Comment by shuen4** [comment]
[ServerPropertiesLAN-2.65_E1.zip](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/files/7968515/ServerPropertiesLAN-2.65_E1.zip)
指令列表:
/ban /ban-ip /banlist /op /deop /pardon /pardon-ip /save-all /save-off /save-on /setidletimeout /whitelist /kick /list /stop

**Comment by shuen4** [comment]
解决了?

**Comment by OrokinLF** [comment]
都正常可以使用，谢了
