### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by iGRemini** [shuen4/MinecraftForge-Mods-ServerPropertiesLAN#7]
方便加下联系方式么，不太会使用，下载下来是文件,不是.java文件，该怎么往后面继续使用呢

**Comment by shuen4** [comment]
[jar](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/releases/download/2.70a/ServerPropertiesLAN_v2.70a_AIO.jar)
[java](https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/raw/master/1.18/src/main/java/com/shuen/splan/splan.java)
